import { Router } from 'express';
import { prisma } from '../config/prisma';
import { requireAuth } from '../middleware/auth_middleware';

export const addressRouter = Router();
addressRouter.use(requireAuth);

addressRouter.get('/', async (req, res, next) => { try { const addresses = await prisma.address.findMany({ where: { userId: req.authUser!.id }, orderBy: [{ isDefault: 'desc' }, { id: 'desc' }] }); res.json({ success: true, data: { addresses } }); } catch (error) { next(error); } });

addressRouter.post('/', async (req, res, next): Promise<void> => { try { const { receiverName, phone, addressLine, city, state, postalCode } = req.body; if (![receiverName, phone, addressLine, city, state, postalCode].every((v) => String(v ?? '').trim())) { res.status(400).json({ success: false, message: '请填写完整的收货地址' }); return; } const count = await prisma.address.count({ where: { userId: req.authUser!.id } }); const makeDefault = Boolean(req.body.isDefault) || count === 0; const address = await prisma.$transaction(async (tx) => { if (makeDefault) await tx.address.updateMany({ where: { userId: req.authUser!.id }, data: { isDefault: false } }); return tx.address.create({ data: { userId: req.authUser!.id, receiverName: String(receiverName).trim(), phone: String(phone).trim(), addressLine: String(addressLine).trim(), city: String(city).trim(), state: String(state).trim(), postalCode: String(postalCode).trim(), isDefault: makeDefault } }); }); res.status(201).json({ success: true, data: { address } }); } catch (error) { next(error); } });

addressRouter.patch('/:id', async (req, res, next): Promise<void> => { try { const old = await prisma.address.findFirst({ where: { id: req.params.id, userId: req.authUser!.id } }); if (!old) { res.status(404).json({ success: false, message: '地址不存在' }); return; } const allowed = ['receiverName', 'phone', 'addressLine', 'city', 'state', 'postalCode'] as const; const data: Record<string, unknown> = {}; for (const key of allowed) if (req.body[key] != null) data[key] = String(req.body[key]).trim(); const address = await prisma.$transaction(async (tx) => { if (req.body.isDefault === true) { await tx.address.updateMany({ where: { userId: req.authUser!.id }, data: { isDefault: false } }); data.isDefault = true; } return tx.address.update({ where: { id: old.id }, data }); }); res.json({ success: true, data: { address } }); } catch (error) { next(error); } });

addressRouter.delete('/:id', async (req, res, next): Promise<void> => { try { const old = await prisma.address.findFirst({ where: { id: req.params.id, userId: req.authUser!.id } }); if (!old) { res.status(404).json({ success: false, message: '地址不存在' }); return; } await prisma.$transaction(async (tx) => { await tx.address.delete({ where: { id: old.id } }); if (old.isDefault) { const nextAddress = await tx.address.findFirst({ where: { userId: req.authUser!.id } }); if (nextAddress) await tx.address.update({ where: { id: nextAddress.id }, data: { isDefault: true } }); } }); res.json({ success: true }); } catch (error) { next(error); } });
