import { Router } from 'express';
import { prisma } from '../config/prisma';
import { requireAuth } from '../middleware/auth_middleware';

export const cartRouter = Router();
cartRouter.use(requireAuth);
const includeProduct = { product: { include: { images: { orderBy: { position: 'asc' as const } }, variants: true, store: true, category: true } }, variant: true };
function present(item: any) { return { id: item.id, quantity: item.quantity, selected: item.selected, variant: item.variant?.name ?? '默认规格', product: { id: item.product.id, name: item.product.name, subtitle: item.product.subtitle, description: item.product.description, price: item.variant?.price ?? item.product.price, originalPrice: item.product.originalPrice, rating: item.product.rating, soldCount: item.product.soldCount, sellerName: item.product.store.name, sellerLocation: item.product.store.location, category: item.product.category.name, images: item.product.images.map((x: any) => x.imageUrl), variants: item.product.variants.map((x: any) => ({ id: x.id, name: x.name })) } }; }
cartRouter.get('/', async (req, res, next) => { try { const rows = await prisma.cartItem.findMany({ where: { userId: req.authUser!.id }, include: includeProduct, orderBy: { createdAt: 'desc' } }); res.json({ success: true, data: { items: rows.map(present) } }); } catch (e) { next(e); } });
cartRouter.post('/', async (req, res, next): Promise<void> => { try { const productId = String(req.body.productId); const quantity = Math.max(1, Math.min(99, Number(req.body.quantity) || 1)); const product = await prisma.product.findFirst({ where: { id: productId, isActive: true }, include: { variants: true } }); if (!product) { res.status(404).json({ success: false, message: '商品不存在或已下架' }); return; } const variant = product.variants.find((x) => x.name === req.body.variantName); const old = await prisma.cartItem.findFirst({ where: { userId: req.authUser!.id, productId, variantId: variant?.id ?? null } }); const row = old ? await prisma.cartItem.update({ where: { id: old.id }, data: { quantity: Math.min(99, old.quantity + quantity) }, include: includeProduct }) : await prisma.cartItem.create({ data: { userId: req.authUser!.id, productId, variantId: variant?.id, quantity }, include: includeProduct }); res.status(201).json({ success: true, data: { item: present(row) } }); } catch (e) { next(e); } });
cartRouter.patch('/:id', async (req, res, next): Promise<void> => { try { const old = await prisma.cartItem.findFirst({ where: { id: req.params.id, userId: req.authUser!.id } }); if (!old) { res.status(404).json({ success: false, message: '购物车商品不存在' }); return; } const data: { quantity?: number; selected?: boolean } = {}; if (req.body.quantity != null) data.quantity = Math.max(1, Math.min(99, Number(req.body.quantity))); if (req.body.selected != null) data.selected = Boolean(req.body.selected); const row = await prisma.cartItem.update({ where: { id: old.id }, data, include: includeProduct }); res.json({ success: true, data: { item: present(row) } }); } catch (e) { next(e); } });
cartRouter.delete('/:id', async (req, res, next): Promise<void> => { try { const result = await prisma.cartItem.deleteMany({ where: { id: req.params.id, userId: req.authUser!.id } }); if (!result.count) { res.status(404).json({ success: false, message: '购物车商品不存在' }); return; } res.json({ success: true }); } catch (e) { next(e); } });
