"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:3000/api", KEY="mallgo_admin_token";
type Product={id:string;name:string;category:string;price:number;stock:number;isActive:boolean;soldCount:number;imageUrl:string;description:string};
type Order={id:string;orderNumber:string;status:string;receiverName:string;phone:string;total:number;createdAt:string;items:{name:string;quantity:number}[]};
type Dashboard={store:{name:string};productCount:number;activeCount:number;orderCount:number;revenue:number};
async function api(path:string,options:RequestInit={}){const token=typeof window!=="undefined"?localStorage.getItem(KEY):null;const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||`请求失败（${r.status}）`);return b.data}
export default function Home(){
 const[token,setToken]=useState<string|null>(null),[user,setUser]=useState<any>(null),[active,setActive]=useState("Overview"),[dashboard,setDashboard]=useState<Dashboard|null>(null),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[editing,setEditing]=useState<Product|null|undefined>(undefined);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const me=await api("/auth/me");if(!["SELLER"].includes(me.user.role))throw new Error("仅审核通过的卖家可以进入商家工作台");const[d,p,o]=await Promise.all([api("/seller/dashboard"),api("/seller/products"),api("/seller/orders")]);setUser(me.user);setDashboard(d);setProducts(p.products);setOrders(o.orders)}catch(e){setError(e instanceof Error?e.message:"加载失败")}finally{setLoading(false)}},[]);
 useEffect(()=>{const t=localStorage.getItem(KEY);setToken(t);if(t)load()},[load]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);try{const d=await api("/auth/login",{method:"POST",body:JSON.stringify({email:f.get("email"),password:f.get("password")})});if(!["SELLER"].includes(d.user.role))throw new Error("仅审核通过的卖家可以进入商家工作台");localStorage.setItem(KEY,d.token);setToken(d.token);await load()}catch(e){setError(e instanceof Error?e.message:"登录失败")}finally{setLoading(false)}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={name:f.get("name"),category:f.get("category"),description:f.get("description"),imageUrl:f.get("imageUrl"),price:Number(f.get("price")),stock:Number(f.get("stock")),isActive:f.get("isActive")==="on"};try{await api(editing?`/seller/products/${editing.id}`:"/seller/products",{method:editing?"PATCH":"POST",body:JSON.stringify(body)});setEditing(undefined);await load()}catch(e){setError(e instanceof Error?e.message:"保存失败")}}
 async function ship(id:string){try{await api(`/seller/orders/${id}/ship`,{method:"PATCH"});await load()}catch(e){setError(e instanceof Error?e.message:"发货失败")}}
 function logout(){localStorage.removeItem(KEY);setToken(null);setUser(null)}
 if(!token)return <main className="loginPage"><section className="loginVisual"><div className="loginBrand"><span>MG</span><b>Mall Go<small>SELLER CONSOLE</small></b></div><h1>专业商家管理后台</h1><p>统一管理商品、库存、订单与经营数据。</p></section><form className="loginPanel" onSubmit={login}><p>WELCOME BACK</p><h2>登录商家后台</h2><label>邮箱<input name="email" type="email" required/></label><label>密码<input name="password" type="password" required/></label>{error&&<div className="loginError">{error}</div>}<button className="primary" disabled={loading}>{loading?"登录中…":"登录"}</button><small>仅审核通过的 SELLER 账号可进入</small></form></main>;
 const titles:any={Overview:"经营概览",Products:"商品管理",Orders:"订单管理"};
 return <main className="shell"><aside className="sidebar"><div className="brand"><span>MG</span><div>Mall Go<small>SELLER CONSOLE</small></div></div><nav>{[["Overview","⌂"],["Products","□"],["Orders","▤"]].map(([x,i])=><button key={x} className={active===x?"active":""} onClick={()=>setActive(x)}><b>{i}</b>{titles[x]}</button>)}</nav><div className="sideBottom"><div className="profile"><div>{user?.name?.slice(0,2).toUpperCase()}</div><span>{user?.name}<small>{user?.email}</small></span></div><button onClick={logout}><b>↪</b>退出登录</button></div></aside><section className="workspace"><header><div><p>{dashboard?.store.name||"SELLER WORKSPACE"}</p><h1>{titles[active]}</h1></div><div className="headerTools"><button className="icon" onClick={load}>↻</button>{active==="Products"&&<button className="primary" onClick={()=>setEditing(null)}>＋ 新增商品</button>}</div></header><div className="content">{error&&<div className="errorBox">{error}<button onClick={()=>setError("")}>×</button></div>}{loading&&<div className="loading">正在同步真实数据…</div>}
 {active==="Overview"&&<><section className="hero"><div><span>STORE PERFORMANCE</span><h2>你好，{user?.name}</h2><p>以下数据直接来自 Mall Go 服务端。</p></div></section><section className="metrics">{[["累计营业额",`RM ${(dashboard?.revenue||0).toFixed(2)}`,"已完成订单"],["订单数",dashboard?.orderCount||0,"当前店铺"],["商品数",dashboard?.productCount||0,"全部商品"],["上架商品",dashboard?.activeCount||0,"正在销售"]].map((x,i)=><article key={String(x[0])}><div className={`metricIcon m${i}`}>{["▰","▤","□","✓"][i]}</div><span>{x[0]}</span><h3>{x[1]}</h3><p className="up">{x[2]}</p></article>)}</section><section className="orders card"><div className="cardHead"><div><span>RECENT ACTIVITY</span><h3>最近订单</h3></div><button onClick={()=>setActive("Orders")}>查看全部 →</button></div><OrderTable orders={orders.slice(0,5)} ship={ship}/></section></>}
 {active==="Products"&&<section className="orders card"><div className="cardHead"><div><span>CATALOG</span><h3>商品列表（{products.length}）</h3></div></div><div className="table"><div className="tr productRow th"><span>商品</span><span>分类</span><span>价格</span><span>库存</span><span>状态</span><span>操作</span></div>{products.map(p=><div className="tr productRow" key={p.id}><span><b>{p.name}</b><small>已售 {p.soldCount}</small></span><span>{p.category}</span><span><b>RM {p.price.toFixed(2)}</b></span><span>{p.stock}</span><span><em className={p.isActive?"paid":"pending"}>● {p.isActive?"已上架":"已下架"}</em></span><span><button onClick={()=>setEditing(p)}>编辑</button></span></div>)}</div></section>}
 {active==="Orders"&&<section className="orders card"><div className="cardHead"><div><span>FULFILMENT</span><h3>订单列表（{orders.length}）</h3></div></div><OrderTable orders={orders} ship={ship}/></section>}</div></section>
 {editing!==undefined&&<div className="modal"><form onSubmit={save}><div className="modalHead"><h2>{editing?"编辑商品":"新增商品"}</h2><button type="button" onClick={()=>setEditing(undefined)}>×</button></div><label>商品名称<input name="name" required defaultValue={editing?.name}/></label><label>分类名称<input name="category" required defaultValue={editing?.category}/></label><label>描述<textarea name="description" required defaultValue={editing?.description}/></label><div className="formGrid"><label>售价（RM）<input name="price" type="number" min="0.01" step="0.01" required defaultValue={editing?.price}/></label><label>库存<input name="stock" type="number" min="0" required defaultValue={editing?.stock}/></label></div><label>图片 URL<input name="imageUrl" type="url" defaultValue={editing?.imageUrl}/></label><label className="check"><input name="isActive" type="checkbox" defaultChecked={editing?.isActive??true}/>立即上架</label><button className="primary">保存商品</button></form></div>}</main>}
function OrderTable({orders,ship}:{orders:Order[];ship:(id:string)=>void}){return <div className="table"><div className="tr th"><span>订单</span><span>收件人</span><span>金额</span><span>状态</span><span>商品</span><span>操作</span></div>{orders.map(o=><div className="tr" key={o.id}><span><b>{o.orderNumber}</b><small>{new Date(o.createdAt).toLocaleString()}</small></span><span>{o.receiverName}<small>{o.phone}</small></span><span><b>RM {o.total.toFixed(2)}</b></span><span><em className="status">{o.status}</em></span><span>{o.items.map(i=>`${i.name} ×${i.quantity}`).join("、")}</span><span>{o.status==="PROCESSING"?<button onClick={()=>ship(o.id)}>发货</button>:"—"}</span></div>)}{!orders.length&&<div className="empty">暂无订单</div>}</div>}
